### ISSUE TITLE
"Your card was declined" when trying billing request

### ISSUE THREAD

**Issue by chooyan-eng** [FlutterHubio/flutterhub#1]
Hi.

It seems billing requests to Stripe are declined with the error below.

![image](https://user-images.githubusercontent.com/20849526/67363228-dd245480-f5a7-11e9-987f-8ea2d15bcb8f.png)

I guess the page is deployed as using Stripe with "test" mode (not production mode).

----
URL:
https://app.flutterhub.io/editor/Ul8ZUdtD1Mf8KqLvi6km

Steps:
Open the URL above > input my credit card information > hit "PAY" button

Error Message:

----

Thanks.

**Comment by chooyan-eng** [comment]
It seems I didn't understand FlutterHub is in the official test date right now.
I tried to use dummy card number and could upgrade the plan.

Thanks.

**Comment by rubencg195** [comment]
Thank you, @chooyan-eng. Yes, we want insiders to be able to test the platform without payment required. Insiders will win free credits as well for their help and feedback after the test period to use the PRO version, after the testing period.
