### ISSUE TITLE
does not show message of "purchase completed"

### ISSUE THREAD

**Issue by victormanuelfrancodev** [FlutterHubio/flutterhub#2]
Does not show message of "purchase completed", So, I have that makes many purchases without knowing that the purchase has already been made
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/27299953/67609541-4edae900-f7c8-11e9-8427-0a1041215ac8.png">

**Comment by rubencg195** [comment]
Thank you, @victormanuelfrancodev. We will investigate the issue.
